# Generated by Django 4.2 on 2023-05-03 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_analyze', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='face_value',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='num_of_stocks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='standard_code',
            field=models.CharField(default='000000', max_length=20),
        ),
        migrations.AlterField(
            model_name='stock',
            name='listing_date',
            field=models.DateField(null=True),
        ),
    ]
