# Generated by Django 4.2 on 2023-05-03 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_analyze', '0002_stock_face_value_stock_num_of_stocks_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='stock',
        ),
    ]
